### ISSUE TITLE
تداخل با اسکریپ Gost

### ISSUE THREAD

**Issue by mr-mr7** [Azumi67/PrivateIP-Tunnel#1]
سلام
اول از همه تشکر میکنم بابت زحماتتون برای ساخت اسکریپت
من از اسکریپت https://github.com/masoudgb/Gost-ip6/issues برای تانل زدن استفاده میکنم
ولی مشکلی ک هست وقتی کنار اسکریپت شما اسکریپت Gost نصب میکنم مشکل پورت میخورم
یعنی وقتی رنج پورت 54,65000 که داخل اسکریپ Gost میتونم تعریف کنم رو اضافه میکنم همه ی پورتا جواب نمیده و یه سریاش مشکل میخوره

**Comment by Azumi67** [comment]
سلام مرسی. منظورتون استفاده از پرایوت ایپی هست یا دو تا تانل کنار هم ؟ چون اگر تانل هست احتمالا به خاطر اختلال در پورت هست .

**Comment by mr-mr7** [comment]
من از اسکریپت شما برای تولید پرایوت ایپی استفاده کردم
و از پرایوت ایپی ها داخل اسکریپ اقای مسعود برای تولید تانل استفاده کردم ولی پورت هاش مشکل داشت
بهشون که گفتم گفتن به خاطر اسکریپ شما هست که تداخل خورده

**Comment by Azumi67** [comment]
> من از اسکریپت شما برای تولید پرایوت ایپی استفاده کردم و از پرایوت ایپی ها داخل اسکریپ اقای مسعود برای تولید تانل استفاده کردم ولی پورت هاش مشکل داشت بهشون که گفتم گفتن به خاطر اسکریپ شما هست که تداخل خورده

برای پرایوت ایپی از این اسکریپت استفاده نمایید. 
https://github.com/Azumi67/6TO4-GRE-IPIP-SIT
به هر صورت تانل های 6to4 gen و سایرشون، در اخر به شما یک ایپی میدن و از اون برای تانل استفاده میکنید. پورت و سایر موارد در تانل اصلی، فوروارد میشه 
شما حتما بررسی کنید که سرویس دیگری و تانل دیگری ندارید که اختلال در پورت شما انداخته باشه
