### ISSUE TITLE
مشکل پهنای باند

### ISSUE THREAD

**Issue by alphamanrays** [Azumi67/PrivateIP-Tunnel#3]
سلام وقت بخیر مهندس عزیز واقعا دمتون گرم بابت این اسکریپت
 من با frp کانفیگ کردم پینگم اوکی هست ولی پهنای باندم رو 10 مگابیت گیر میکنه مشکل از چی میتونه باشه ؟
با udpraw هم کانفیگ کردم وصل میشه و ترافیک رد و بدل میشه ولی در حدی که گوگل رو هم باز نمیکنه
بنظرتون مشکل کار من چی هست ؟

**Comment by Azumi67** [comment]
سلام. شما به نظر بیشتر مشکل سرور دارید چون چنین مشکلی نباید بر روی این تانل ها تجربه کنید مگر اینکه لیمیت شده باشید.
